name: Release APK

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.gitignore'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "PGHOST=${{ secrets.PGHOST }}" >> .env
          echo "PGPORT=${{ secrets.PGPORT }}" >> .env
          echo "PGDATABASE=${{ secrets.PGDATABASE }}" >> .env
          echo "PGUSER=${{ secrets.PGUSER }}" >> .env
          echo "PGPASSWORD=${{ secrets.PGPASSWORD }}" >> .env
          echo "SMTP_EMAIL=${{ secrets.SMTP_EMAIL }}" >> .env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
          echo "CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }}" >> .env

      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.0"
          channel: stable

      - run: flutter pub get

      - run: flutter build apk --release

      - name: Delete old release
        run: gh release delete latest --yes --cleanup-tag 2>/dev/null || true
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true

      - uses: softprops/action-gh-release@v2
        with:
          name: "Latest"
          tag_name: "latest"
          files: build/app/outputs/flutter-apk/app-release.apk
